// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiCarCatalogMakesByMakeIdModelsData, GetApiCarCatalogMakesByMakeIdModelsResponses, GetApiCarCatalogMakesData, GetApiCarCatalogMakesResponses, GetApiCarCatalogMakesSearchData, GetApiCarCatalogMakesSearchResponses, GetApiCarsByIdData, GetApiCarsByIdResponses, GetApiCarsData, GetApiCarsResponses, GetApiUserMeData, GetApiUserMeResponses, PostApiAuthLoginData, PostApiAuthLoginResponses, PostApiAuthLogoutData, PostApiAuthLogoutResponses, PostApiAuthRefreshData, PostApiAuthRefreshResponses, PostApiAuthRegisterData, PostApiAuthRegisterResponses, PostApiCarsByIdImagesData, PostApiCarsByIdImagesResponses, PostApiCarsData, PostApiCarsResponses, PutApiCarsByIdImagesByImageIdSetMainData, PutApiCarsByIdImagesByImageIdSetMainResponses, PutApiUserAvatarData, PutApiUserAvatarResponses, PutApiUserPasswordData, PutApiUserPasswordResponses, PutApiUserProfileData, PutApiUserProfileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRegisterData, ThrowOnError>) => (options?.client ?? client).post<PostApiAuthRegisterResponses, unknown, ThrowOnError>({
    url: '/api/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLoginData, ThrowOnError>) => (options?.client ?? client).post<PostApiAuthLoginResponses, unknown, ThrowOnError>({
    url: '/api/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postApiAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLogoutData, ThrowOnError>) => (options?.client ?? client).post<PostApiAuthLogoutResponses, unknown, ThrowOnError>({ url: '/api/auth/logout', ...options });

export const postApiAuthRefresh = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRefreshData, ThrowOnError>) => (options?.client ?? client).post<PostApiAuthRefreshResponses, unknown, ThrowOnError>({
    url: '/api/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getApiCars = <ThrowOnError extends boolean = false>(options?: Options<GetApiCarsData, ThrowOnError>) => (options?.client ?? client).get<GetApiCarsResponses, unknown, ThrowOnError>({ url: '/api/cars', ...options });

export const postApiCars = <ThrowOnError extends boolean = false>(options?: Options<PostApiCarsData, ThrowOnError>) => (options?.client ?? client).post<PostApiCarsResponses, unknown, ThrowOnError>({
    url: '/api/cars',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postApiCarsByIdImages = <ThrowOnError extends boolean = false>(options: Options<PostApiCarsByIdImagesData, ThrowOnError>) => (options.client ?? client).post<PostApiCarsByIdImagesResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/cars/{id}/images',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const putApiCarsByIdImagesByImageIdSetMain = <ThrowOnError extends boolean = false>(options: Options<PutApiCarsByIdImagesByImageIdSetMainData, ThrowOnError>) => (options.client ?? client).put<PutApiCarsByIdImagesByImageIdSetMainResponses, unknown, ThrowOnError>({ url: '/api/cars/{id}/images/{imageId}/set-main', ...options });

export const getApiCarsById = <ThrowOnError extends boolean = false>(options: Options<GetApiCarsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiCarsByIdResponses, unknown, ThrowOnError>({ url: '/api/cars/{id}', ...options });

export const getApiCarCatalogMakes = <ThrowOnError extends boolean = false>(options?: Options<GetApiCarCatalogMakesData, ThrowOnError>) => (options?.client ?? client).get<GetApiCarCatalogMakesResponses, unknown, ThrowOnError>({ url: '/api/car-catalog/makes', ...options });

export const getApiCarCatalogMakesSearch = <ThrowOnError extends boolean = false>(options?: Options<GetApiCarCatalogMakesSearchData, ThrowOnError>) => (options?.client ?? client).get<GetApiCarCatalogMakesSearchResponses, unknown, ThrowOnError>({ url: '/api/car-catalog/makes/search', ...options });

export const getApiCarCatalogMakesByMakeIdModels = <ThrowOnError extends boolean = false>(options: Options<GetApiCarCatalogMakesByMakeIdModelsData, ThrowOnError>) => (options.client ?? client).get<GetApiCarCatalogMakesByMakeIdModelsResponses, unknown, ThrowOnError>({ url: '/api/car-catalog/makes/{makeId}/models', ...options });

export const getApiUserMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiUserMeResponses, unknown, ThrowOnError>({ url: '/api/user/me', ...options });

export const putApiUserPassword = <ThrowOnError extends boolean = false>(options?: Options<PutApiUserPasswordData, ThrowOnError>) => (options?.client ?? client).put<PutApiUserPasswordResponses, unknown, ThrowOnError>({
    url: '/api/user/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const putApiUserProfile = <ThrowOnError extends boolean = false>(options?: Options<PutApiUserProfileData, ThrowOnError>) => (options?.client ?? client).put<PutApiUserProfileResponses, unknown, ThrowOnError>({
    url: '/api/user/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const putApiUserAvatar = <ThrowOnError extends boolean = false>(options?: Options<PutApiUserAvatarData, ThrowOnError>) => (options?.client ?? client).put<PutApiUserAvatarResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/user/avatar',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});
