// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApproveDealershipRequest = {
    approve: boolean;
    notes?: string | null;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type CreateCarRequest = {
    makeId: string;
    modelId: string;
    year: number;
    firstRegistrationDate: string;
    mileage: number;
    previousOwners: number;
    fuelType: string;
    enginePower: number;
    transmission: string;
    color: string;
    equipmentAndDetails?: string | null;
    price: number;
};

export type CreateCommentRequest = {
    content: string;
};

export type CreateDealershipRequest = {
    name: string;
    description?: string | null;
    address: string;
    city: string;
    phoneNumber: string;
    email?: string | null;
    website?: string | null;
    taxNumber?: string | null;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type InviteWorkerRequest = {
    userId: string;
    role: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type MarkMessagesReadRequest = {
    senderId: string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    name: string;
    surname: string;
    email: string;
    phoneNumber: string;
    username: string;
    password: string;
};

export type ResetPasswordRequest = {
    token: string;
    newPassword: string;
};

export type Role = 0 | 1;

export type SendFriendRequestRequest = {
    addresseeId: string;
};

export type TransferOwnershipRequest = {
    newOwnerId: string;
};

export type UpdateCarRequest = {
    makeId: string;
    modelId: string;
    year: number;
    firstRegistrationDate: string;
    mileage: number;
    previousOwners: number;
    fuelType: string;
    enginePower: number;
    transmission: string;
    color: string;
    equipmentAndDetails?: string | null;
    price: number;
};

export type UpdateCommentRequest = {
    content: string;
};

export type UpdateDealershipRequest = {
    name?: string | null;
    description?: string | null;
    address?: string | null;
    city?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    website?: string | null;
    taxNumber?: string | null;
};

export type UpdateProfileRequest = {
    name?: string | null;
    surname?: string | null;
    phoneNumber?: string | null;
};

export type UpdateUserRoleRequest = {
    role: Role;
};

export type UpdateWorkerRoleRequest = {
    role: string;
};

export type PostApiAuthRegisterData = {
    body?: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthRefreshData = {
    body?: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type PostApiAuthRefreshResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthForgotPasswordData = {
    body?: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/forgot-password';
};

export type PostApiAuthForgotPasswordResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthResetPasswordData = {
    body?: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type PostApiAuthResetPasswordResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        makeId?: string;
        modelId?: string;
        yearFrom?: number;
        yearTo?: number;
        priceFrom?: number;
        priceTo?: number;
        mileageTo?: number;
        fuelType?: string;
        search?: string;
        sellerId?: string;
    };
    url: '/api/cars';
};

export type GetApiCarsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiCarsData = {
    body?: CreateCarRequest;
    path?: never;
    query?: never;
    url: '/api/cars';
};

export type PostApiCarsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiCarsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cars/{id}';
};

export type DeleteApiCarsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cars/{id}';
};

export type GetApiCarsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiCarsByIdData = {
    body?: UpdateCarRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cars/{id}';
};

export type PutApiCarsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiCarsByIdImagesData = {
    body?: {
        files?: Array<Blob | File>;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cars/{id}/images';
};

export type PostApiCarsByIdImagesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiCarsByIdImagesByImageIdData = {
    body?: never;
    path: {
        id: number;
        imageId: number;
    };
    query?: never;
    url: '/api/cars/{id}/images/{imageId}';
};

export type DeleteApiCarsByIdImagesByImageIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiCarsByIdImagesByImageIdSetMainData = {
    body?: never;
    path: {
        id: number;
        imageId: number;
    };
    query?: never;
    url: '/api/cars/{id}/images/{imageId}/set-main';
};

export type PutApiCarsByIdImagesByImageIdSetMainResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarCatalogMakesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-catalog/makes';
};

export type GetApiCarCatalogMakesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarCatalogMakesSearchData = {
    body?: never;
    path?: never;
    query?: {
        query?: string;
    };
    url: '/api/car-catalog/makes/search';
};

export type GetApiCarCatalogMakesSearchResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarCatalogMakesByMakeIdModelsData = {
    body?: never;
    path: {
        makeId: string;
    };
    query?: never;
    url: '/api/car-catalog/makes/{makeId}/models';
};

export type GetApiCarCatalogMakesByMakeIdModelsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiChatConversationByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/api/chat/conversation/{userId}';
};

export type GetApiChatConversationByUserIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiChatConversationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/conversations';
};

export type GetApiChatConversationsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiChatMarkReadData = {
    body?: MarkMessagesReadRequest;
    path?: never;
    query?: never;
    url: '/api/chat/mark-read';
};

export type PostApiChatMarkReadResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiChatRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/requests';
};

export type GetApiChatRequestsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiChatRequestsByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/chat/requests/{userId}';
};

export type DeleteApiChatRequestsByUserIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiChatRequestsByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/api/chat/requests/{userId}';
};

export type GetApiChatRequestsByUserIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiChatRequestsByUserIdAcceptData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/chat/requests/{userId}/accept';
};

export type PostApiChatRequestsByUserIdAcceptResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarsByCarIdCommentsData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/cars/{carId}/comments';
};

export type GetApiCarsByCarIdCommentsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiCarsByCarIdCommentsData = {
    body?: CreateCommentRequest;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/cars/{carId}/comments';
};

export type PostApiCarsByCarIdCommentsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiCommentsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comments/{id}';
};

export type DeleteApiCommentsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiCommentsByIdData = {
    body?: UpdateCommentRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comments/{id}';
};

export type PutApiCommentsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDealershipsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        ownerId?: string;
    };
    url: '/api/dealerships';
};

export type GetApiDealershipsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiDealershipsData = {
    body?: CreateDealershipRequest;
    path?: never;
    query?: never;
    url: '/api/dealerships';
};

export type PostApiDealershipsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDealershipsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/dealerships/{id}';
};

export type GetApiDealershipsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiDealershipsByIdData = {
    body?: UpdateDealershipRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/dealerships/{id}';
};

export type PutApiDealershipsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDealershipsPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dealerships/pending';
};

export type GetApiDealershipsPendingResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiDealershipsByIdApproveData = {
    body?: ApproveDealershipRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/dealerships/{id}/approve';
};

export type PostApiDealershipsByIdApproveResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiDealershipsByIdWorkersInviteData = {
    body?: InviteWorkerRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/dealerships/{id}/workers/invite';
};

export type PostApiDealershipsByIdWorkersInviteResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDealershipsByIdWorkersData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/dealerships/{id}/workers';
};

export type GetApiDealershipsByIdWorkersResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiDealershipsWorkersByWorkerIdData = {
    body?: never;
    path: {
        workerId: number;
    };
    query?: never;
    url: '/api/dealerships/workers/{workerId}';
};

export type DeleteApiDealershipsWorkersByWorkerIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDealershipsWorkersByWorkerIdData = {
    body?: never;
    path: {
        workerId: number;
    };
    query?: never;
    url: '/api/dealerships/workers/{workerId}';
};

export type GetApiDealershipsWorkersByWorkerIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiDealershipsWorkersByWorkerIdRespondData = {
    body?: boolean;
    path: {
        workerId: number;
    };
    query?: never;
    url: '/api/dealerships/workers/{workerId}/respond';
};

export type PostApiDealershipsWorkersByWorkerIdRespondResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDealershipsWorkersInvitationsPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dealerships/workers/invitations/pending';
};

export type GetApiDealershipsWorkersInvitationsPendingResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiDealershipsMyWorkerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/dealerships/my/worker';
};

export type GetApiDealershipsMyWorkerResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiDealershipsWorkersByWorkerIdRoleData = {
    body?: UpdateWorkerRoleRequest;
    path: {
        workerId: number;
    };
    query?: never;
    url: '/api/dealerships/workers/{workerId}/role';
};

export type PutApiDealershipsWorkersByWorkerIdRoleResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiDealershipsByIdTransferOwnershipData = {
    body?: TransferOwnershipRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/dealerships/{id}/transfer-ownership';
};

export type PostApiDealershipsByIdTransferOwnershipResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiDealershipsWorkersByWorkerIdStatusData = {
    body?: boolean;
    path: {
        workerId: number;
    };
    query?: never;
    url: '/api/dealerships/workers/{workerId}/status';
};

export type PutApiDealershipsWorkersByWorkerIdStatusResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiFavouritesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/favourites';
};

export type GetApiFavouritesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiFavouritesByCarIdData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/favourites/{carId}';
};

export type DeleteApiFavouritesByCarIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiFavouritesByCarIdData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/favourites/{carId}';
};

export type PostApiFavouritesByCarIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiFavouritesByCarIdCheckData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/favourites/{carId}/check';
};

export type GetApiFavouritesByCarIdCheckResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiFavouritesByCarIdToggleData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/favourites/{carId}/toggle';
};

export type PostApiFavouritesByCarIdToggleResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiFriendsRequestData = {
    body?: SendFriendRequestRequest;
    path?: never;
    query?: never;
    url: '/api/friends/request';
};

export type PostApiFriendsRequestResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiFriendsRequestByIdAcceptData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/friends/request/{id}/accept';
};

export type PostApiFriendsRequestByIdAcceptResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiFriendsRequestByIdRejectData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/friends/request/{id}/reject';
};

export type PostApiFriendsRequestByIdRejectResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiFriendsRequestByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/friends/request/{id}';
};

export type DeleteApiFriendsRequestByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiFriendsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/friends';
};

export type GetApiFriendsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiFriendsRequestsPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/friends/requests/pending';
};

export type GetApiFriendsRequestsPendingResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiFriendsByFriendIdData = {
    body?: never;
    path: {
        friendId: string;
    };
    query?: never;
    url: '/api/friends/{friendId}';
};

export type DeleteApiFriendsByFriendIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type GetApiUserMeResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserSearchData = {
    body?: never;
    path?: never;
    query?: {
        username?: string;
        limit?: number;
    };
    url: '/api/user/search';
};

export type GetApiUserSearchResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserPasswordData = {
    body?: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/user/password';
};

export type PutApiUserPasswordResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserProfileData = {
    body?: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/user/profile';
};

export type PutApiUserProfileResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserAvatarData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/user/avatar';
};

export type PutApiUserAvatarResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserAdminUsersData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        search?: string;
    };
    url: '/api/user/admin/users';
};

export type GetApiUserAdminUsersResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiUserAdminUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/user/admin/users/{id}';
};

export type DeleteApiUserAdminUsersByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserAdminUsersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/user/admin/users/{id}';
};

export type GetApiUserAdminUsersByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserAdminUsersByIdRoleData = {
    body?: UpdateUserRoleRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/user/admin/users/{id}/role';
};

export type PutApiUserAdminUsersByIdRoleResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserAdminUsersByIdProfileData = {
    body?: UpdateProfileRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/user/admin/users/{id}/profile';
};

export type PutApiUserAdminUsersByIdProfileResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserAdminUsersByIdAvatarData = {
    body?: {
        file?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/user/admin/users/{id}/avatar';
};

export type PutApiUserAdminUsersByIdAvatarResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiUserAdminUsersByIdImpersonateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/user/admin/users/{id}/impersonate';
};

export type PostApiUserAdminUsersByIdImpersonateResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiViewHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/view-history';
};

export type GetApiViewHistoryResponses = {
    /**
     * Success
     */
    200: unknown;
};
