// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type CreateCarRequest = {
    makeId: string;
    modelId: string;
    year: number;
    firstRegistrationDate: string;
    mileage: number;
    previousOwners: number;
    fuelType: string;
    enginePower: number;
    transmission: string;
    color: string;
    equipmentAndDetails?: string | null;
    price: number;
};

export type CreateCommentRequest = {
    content: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    name: string;
    surname: string;
    email: string;
    phoneNumber: string;
    username: string;
    password: string;
};

export type UpdateCommentRequest = {
    content: string;
};

export type UpdateProfileRequest = {
    name?: string | null;
    surname?: string | null;
    phoneNumber?: string | null;
};

export type PostApiAuthRegisterData = {
    body?: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthRefreshData = {
    body?: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type PostApiAuthRefreshResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        makeId?: string;
        modelId?: string;
        yearFrom?: number;
        yearTo?: number;
        priceFrom?: number;
        priceTo?: number;
        mileageTo?: number;
        fuelType?: string;
    };
    url: '/api/cars';
};

export type GetApiCarsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiCarsData = {
    body?: CreateCarRequest;
    path?: never;
    query?: never;
    url: '/api/cars';
};

export type PostApiCarsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiCarsByIdImagesData = {
    body?: {
        files?: Array<Blob | File>;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cars/{id}/images';
};

export type PostApiCarsByIdImagesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiCarsByIdImagesByImageIdSetMainData = {
    body?: never;
    path: {
        id: number;
        imageId: number;
    };
    query?: never;
    url: '/api/cars/{id}/images/{imageId}/set-main';
};

export type PutApiCarsByIdImagesByImageIdSetMainResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cars/{id}';
};

export type GetApiCarsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarCatalogMakesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-catalog/makes';
};

export type GetApiCarCatalogMakesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarCatalogMakesSearchData = {
    body?: never;
    path?: never;
    query?: {
        query?: string;
    };
    url: '/api/car-catalog/makes/search';
};

export type GetApiCarCatalogMakesSearchResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarCatalogMakesByMakeIdModelsData = {
    body?: never;
    path: {
        makeId: string;
    };
    query?: never;
    url: '/api/car-catalog/makes/{makeId}/models';
};

export type GetApiCarCatalogMakesByMakeIdModelsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarsByCarIdCommentsData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/cars/{carId}/comments';
};

export type GetApiCarsByCarIdCommentsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiCarsByCarIdCommentsData = {
    body?: CreateCommentRequest;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/cars/{carId}/comments';
};

export type PostApiCarsByCarIdCommentsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiCommentsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comments/{id}';
};

export type DeleteApiCommentsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiCommentsByIdData = {
    body?: UpdateCommentRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/comments/{id}';
};

export type PutApiCommentsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiFavouritesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/favourites';
};

export type GetApiFavouritesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiFavouritesByCarIdData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/favourites/{carId}';
};

export type DeleteApiFavouritesByCarIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiFavouritesByCarIdData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/favourites/{carId}';
};

export type PostApiFavouritesByCarIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiFavouritesByCarIdCheckData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/favourites/{carId}/check';
};

export type GetApiFavouritesByCarIdCheckResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiFavouritesByCarIdToggleData = {
    body?: never;
    path: {
        carId: number;
    };
    query?: never;
    url: '/api/favourites/{carId}/toggle';
};

export type PostApiFavouritesByCarIdToggleResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type GetApiUserMeResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserPasswordData = {
    body?: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/user/password';
};

export type PutApiUserPasswordResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserProfileData = {
    body?: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/user/profile';
};

export type PutApiUserProfileResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserAvatarData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/user/avatar';
};

export type PutApiUserAvatarResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiViewHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/view-history';
};

export type GetApiViewHistoryResponses = {
    /**
     * Success
     */
    200: unknown;
};
