// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

export type CreateCarRequest = {
    makeId: string;
    modelId: string;
    year: number;
    firstRegistrationDate: string;
    mileage: number;
    previousOwners: number;
    fuelType: string;
    enginePower: number;
    transmission: string;
    color: string;
    equipmentAndDetails?: string | null;
    price: number;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    name: string;
    surname: string;
    email: string;
    phoneNumber: string;
    username: string;
    password: string;
};

export type UpdateProfileRequest = {
    name?: string | null;
    surname?: string | null;
    phoneNumber?: string | null;
};

export type PostApiAuthRegisterData = {
    body?: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiAuthRefreshData = {
    body?: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type PostApiAuthRefreshResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        makeId?: string;
        modelId?: string;
        yearFrom?: number;
        yearTo?: number;
        priceFrom?: number;
        priceTo?: number;
        mileageTo?: number;
        fuelType?: string;
    };
    url: '/api/cars';
};

export type GetApiCarsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiCarsData = {
    body?: CreateCarRequest;
    path?: never;
    query?: never;
    url: '/api/cars';
};

export type PostApiCarsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/cars/{id}';
};

export type GetApiCarsByIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarApiMakesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/car-api/makes';
};

export type GetApiCarApiMakesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarApiMakesSearchData = {
    body?: never;
    path?: never;
    query?: {
        query?: string;
    };
    url: '/api/car-api/makes/search';
};

export type GetApiCarApiMakesSearchResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiCarApiMakesByMakeIdModelsData = {
    body?: never;
    path: {
        makeId: string;
    };
    query?: never;
    url: '/api/car-api/makes/{makeId}/models';
};

export type GetApiCarApiMakesByMakeIdModelsResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type GetApiUserMeResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserPasswordData = {
    body?: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/user/password';
};

export type PutApiUserPasswordResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserProfileData = {
    body?: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/user/profile';
};

export type PutApiUserProfileResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PutApiUserAvatarData = {
    body?: {
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/user/avatar';
};

export type PutApiUserAvatarResponses = {
    /**
     * Success
     */
    200: unknown;
};
